### PR TITLE
BUG fix log plots with constants

### LINKED ISSUE #67: fix bug in log plots with constant values
Something is going wrong in log plots where all the points have a fixed value, e.g. a flat line.  bounding box is mis calculated, resulting in math domain error for a log

### PR DESCRIPTION
**Pull request by beckermr**
This PR fixes log plots with constants in them. 

Closes #67

### CODE REVIEW

**Comment by beckermr** [comment]
@esheldon This PR probably needs some work still. I did look through the examples with this branch and they all look pretty good, so I don't think I broke anything. 

However, the approach is new. In the case of log axes, I am taking log10 of the limits and then doing the same computations biggles normally does for linear axes. I then transform back to linear space at the end. 

I also added ordering tests so that the range of the axes always has xmin < xmax. This might conflict with support for reversed axes? I am not sure.

**Comment by esheldon** [comment]
I do think reverse axes are supposed to be supported

**Comment by beckermr** [comment]
Ahhh ok. I removed the reordering anyways since it was needed to offset another bug.

**Comment by beckermr** [comment]
Hmmm. Reverse axes do not work on master.

**Comment by beckermr** [comment]
@esheldon I am going to go ahead and merge.

**Comment by esheldon** [comment]
sorry I've been swamped with the day job :)

Did you get reverse axes working?

**Comment by beckermr** [comment]
Reversed axes are not actually supported even in master. We should make a separate issue for that.

**Pull request merged**
