### PR TITLE
ENH add travis CI and tests

### LINKED ISSUE #39: make biggles work properly without a ~/.biggles file
currently biggles behaves bizarrely without ~/.biggles in place

### LINKED ISSUE #45: Add a test suite
A test suite would make the development much easier. This could be implemented using the [unittest](https://docs.python.org/3.4/library/unittest.html#module-unittest) module, which is part of the standard library. As a starting point, one could just run the examples scripts, and make sure that they don't raise an  error.

### LINKED ISSUE #46: Use a continuous integration (CI) service
Using a CI service such as [Travis](https://travis-ci.org) would help chasing out bugs. However, for this to be really useful, we would need a testsuite first (see issue #45).

### PR DESCRIPTION
**Pull request by beckermr**
Changes here:

1. I added some test cases with `unittest`.
2. I changed the `config.ini` from a file to a string in python. This procedure works for both python 2 and 3. It also eliminates the pain of convincing `setuptools`/`distutils` to install non-python source files in every different kind of invocation.

One final thing is that I changed the package name from `python2-biggles` to just `biggles`. We should be able to push to pypi with this name.

Closes #45 
Closes #46
Closes #39

### CODE REVIEW

**Comment by beckermr** [comment]
@esheldon Take a look and leave any comments. Should be ready to merge.

**Comment by beckermr** [comment]
@esheldon it looks like your commit to master has created a merge conflict with this PR. Whoops! :)

**Comment by esheldon** [comment]
looks like just removal of a comment

**Comment by esheldon** [comment]
regarding the setuptools issue, I'm not the only one

https://webcache.googleusercontent.com/search?q=cache:ghAXAUiUNfQJ:https://cournape.wordpress.com/2008/07/05/using-stow-with-setuptools/+&cd=4&hl=en&ct=clnk&gl=us&client=ubuntu

This is a real issue; in big data management projects (e.g. LSST DM)  the directories are *never* on the pythonpath during installation.

**Comment by esheldon** [comment]
So the question is, what is the advantage of setuptools?

**Comment by beckermr** [comment]
There are two here. 

1. For dev, you can just type 'python setup.py develop' and it just puts the local checkout you have on your Python path. No having to install or reinstall to test things. 

2. For testing, setup tools can build and run your test suite for you while also doing Python 2 to Python 3 conversion. 

This last thing is the only way I could get Travis to work for testing on all Python versions. 

Plus the build script is a lot simpler which should make it easier to maintain.

**Comment by esheldon** [comment]
we travis working for fitsio using distutils.

as for testing, I do always install it. I guess I am used to it and don't mind.

There is no way I can use this easily with our modules setup at BNL, and I wouldn't expect others to have to deal with this problem.  I wonder if there is a way to turn off that refusal to install in the setup.py itself.  I haven't yet found a way

**Comment by beckermr** [comment]
I am confused. What about this is not usable at BNL?

**Comment by beckermr** [comment]
moving the default config from a file to a Python string will work anywhere. You just need a bit of tmp disk. Is that really an issue?

**Comment by esheldon** [comment]
If you type `python setup.py install --prefix=/some/random/place` setuptools will refuse unless it is on your PYTHONPATH, for no good reason that I can see.

This breaks automatic systems like `eups` and others, e.g. used by LSST, that need to be able to install gazillions of versions of packages at any time without them all being on the PYTHONPATH.  Then you load them later.

That's the issue.

Note sure what you meant by `moving the default config from a file to a Python string will work anywhere`

**Comment by beckermr** [comment]
Ahhhh ok. Good to know. I will reconfigure the PR to use distutils.

**Comment by beckermr** [comment]
I thought maybe the BNL issue was due to scratch space or something which is why I was asking about the config. I think I can rework it to use the io module with some Python 2 or three trickery.

**Comment by esheldon** [comment]
Thanks. And thanks for setting up travis by the way, it can be tricky.

**Comment by beckermr** [comment]
Yeaaaaah. Travis config is a mess TBH. :)

**Comment by beckermr** [comment]
OK. Take another look @esheldon. This should be good to go.

**Comment by beckermr** [comment]
@esheldon Let's not push to master until this one is merged?

**Comment by esheldon** [comment]
thanks for going with distutils, and the bug fix. looks good.  lets give it a try.

**Pull request merged**
