### PR TITLE
WIP new digs!

### PR DESCRIPTION
**Pull request by beckermr**
To do:
 - [x] Render examples with jinja2 
 - [x] clean up code
 - [ ] move to master
 - [x] setup Travis

### CODE REVIEW

**Comment by beckermr** [comment]
screen shot 2017-03-15 at 10 22 23 pm

**Comment by beckermr** [comment]
This code has to be moved to `/docs` in master and then travis will build the website on commits to master.

**Comment by esheldon** [comment]
Looks good from the image.  Is there a way to view it in full?

**Comment by beckermr** [comment]
Yeah. Pull this branch and the build by running render_index.py. You will need jinja2 and pygments. Then just open index.html. All of the JavaScript and CSS for Twitter bootstrap are pulled on the fly.

**Comment by beckermr** [comment]
Sorry. That is render_website.py

**Comment by esheldon** [comment]
I found a few issues with page rendering.  Looks like there might have been some assumptions about screen sizes and font sizes.

First, in the quick start I think this should be rendered as python instead of red
quick-start1

In the examples I see the navigation circles can show up on top of things, and the left right arrows can be covering the code

example1-2

example2-1

I think those things might be fixable using div/table type separations

**Comment by esheldon** [comment]
Note also, the images sometimes are to the right, sometimes below the code.

**Comment by beckermr** [comment]
Thanks for taking a look!

Some of this is taste and other bits are features/bugs. 

I am happy to change the other Python code bits. I thought inline styling by bootstrap looked good for those bits code that are good to call out, like install instructions. 

So the examples being stacked or not depends on the screen size and their size. Bootstrap is designed so that if you look at this on a mobile device, it rearranges stuff to make it more readable. This is why the examples show up differently. Forcing all side by side would break this feature. 

The controls are a bit see through since they are meant to be on top of the examples. I can make them less opaque. 

We can move the controls below the content too.

**Comment by beckermr** [comment]
@esheldon This is done and the new website is live. It lives in its own repo. Modify the `website` branch there to make changes. Then travis will build the site and force push the new one to `master` on that repo.

**Pull request closed without merging**
