### PR TITLE
Jupyter inline

### PR DESCRIPTION
**Pull request by esheldon**
addresses issue #104 

I also added some example ipython notebooks that could be used in documentation

### CODE REVIEW

**Comment by beckermr** [comment]
Awesome! Can you add some docs to the markdown in the docs folder?

It will build automatically when pushed to master. 

Maybe a new section in the overview in the reference guide?

**Comment by esheldon** [comment]
It might be good to start the quick ref with an interactive example using the convenience function `plot()`

**Comment by beckermr** [comment]
Great idea! We should make a separate issue for this.

**Comment by beckermr** [comment]
Feel free to merge when you are happy. Def make some notes in the changelog if you have not already.

**Pull request merged**
