### PR TITLE
ENH Add += to containers

### LINKED ISSUE #78: Allow += syntax for adding components to containers

### PR DESCRIPTION
**Pull request by beckermr**
Closes #78

### CODE REVIEW

**Comment by esheldon** [comment]
Should this also support adding a sequence of plot items?
```
plt=FramedPlot()
plt += [points1,curve1,..]
```

Note I've added the ability for `PlotKey` to do `.add` as well, would be good to have it support this.

**Comment by beckermr** [comment]
Support for iterabkes is a great idea. Will do.

**Comment by esheldon** [comment]
What you have so far works for me

**Comment by beckermr** [comment]
Hmmm. Did you try a tuple too? I had some issues but that was with a previous version.

**Comment by esheldon** [comment]
I just ran the example

**Pull request merged**
