### PR TITLE
Bundle plotutils

### LINKED ISSUE #140: bundle plotutils
plotutils is abandoned and now does not compile against recent libpng

the patch is trivial, but there is no one to send the patch to!

The easy thing would be to bundle it.

### PR DESCRIPTION
**Pull request by esheldon**
closes #140 

This probably still needs some work.

### CODE REVIEW

**Comment by esheldon** [comment]
looks like travis is not working...  again

**Comment by esheldon** [comment]
I set up github actions for tests, looks good on linux with system python and miniconda.

I can't develop on a mac unfortunately.

**Comment by beckermr** [comment]
You can setup github actions to run the tests on osx.

**Comment by esheldon** [comment]
Yeah I know, but since it is likely to fail its kind of pointless.

For example does the macos image even come with x11 libraries?  Unlikely.

**Comment by beckermr** [comment]
We build against osx all the time with conda-forge and link to x11. I am sure this is possible but you may not want to spend time on it.

**Comment by esheldon** [comment]
hmm, macos actions didn't go

**Comment by esheldon** [comment]
```
https://github.com/actions/virtual-environments/issues/771
```

**Comment by beckermr** [comment]
use brew. it's on there

**Comment by beckermr** [comment]
yup they have brew: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

**Comment by beckermr** [comment]
also osx has system x11

i'd ignore python 3.5

**Comment by beckermr** [comment]
This works now on osx @esheldon. Nice work on xquartz!

**Review by beckermr — COMMENTED** [review]
Looking good!

I have on big comment. I think the target here is a conda package. It will make things a lot easier later if we can make sure the build respects environment variables like CFLAGS, LDFLAGS, etc. Many times, one has to ship a patch to the setup.py to get the flags in the right spot. The conda build scripts will set these and they have to be used or the package won't build correctly.

**Comment by esheldon** [comment]
> Looking good!
> 
> I have on big comment. I think the target here is a conda package. It will make things a lot easier later if we can make sure the build respects environment variables like CFLAGS, LDFLAGS, etc. Many times, one has to ship a patch to the setup.py to get the flags in the right spot. The conda build scripts will set these and they have to be used or the package won't build correctly.

I tried including those FLAGS (using your code from fitsio) and it would not build.

**Comment by esheldon** [comment]
no idea why this is suddenly failing, maybe some change in the underlying container

**Comment by esheldon** [comment]
> Looking good!
> 
> I have on big comment. I think the target here is a conda package. It will make things a lot easier later if we can make sure the build respects environment variables like CFLAGS, LDFLAGS, etc. Many times, one has to ship a patch to the setup.py to get the flags in the right spot. The conda build scripts will set these and they have to be used or the package won't build correctly.

actually maybe I partly misunderstood.   My issue was when I passed on some FLAGS to the plotutils build, using your code from fitsio setup.py, it failed.  Is that the place where you have concern or is it in building the extension itself, which links against the .a file?

**Comment by beckermr** [comment]
Yeah sorry. I mean the flags defined when one actually runs conda build in a recipe. You don't need to pass them here. We just need to make sure the build grabs any flags defined in the env and actually uses them. It should also avoid hardcoded paths to libraries.

**Comment by esheldon** [comment]
Can you help making it conda ready?

**Comment by beckermr** [comment]
Sure but probably not today.

**Comment by esheldon** [comment]
no big hurry.  Shall we merge this and make a new issue for conda readiness?

**Comment by beckermr** [comment]
Yeah I think that is best. TBH, we can just ship a patch in the conda recipe. We don't actually know what is needed so better to try and build it first.

**Pull request merged**
